# Generated by Django 4.1.5 on 2023-01-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(default='Pessoa Física', max_length=15)),
                ('nome', models.CharField(max_length=50)),
                ('rg', models.CharField(blank=True, max_length=11, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=14, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_cliente')),
                ('tipo_end', models.CharField(default='Residencial', max_length=15)),
                ('rua', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('compl', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
    ]
