# Generated by Django 5.2.1 on 2025-05-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposits', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True)),
                ('obs', models.CharField(blank=True, max_length=10, null=True)),
                ('saldo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.CharField(blank=True, max_length=6, null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateField(blank=True)),
                ('valor', models.CharField(blank=True, max_length=10, null=True)),
                ('movimento', models.CharField(blank=True, max_length=10, null=True)),
                ('hora', models.TimeField(blank=True)),
                ('tipo_pgto', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
