# Generated by Django 4.1.5 on 2023-04-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
    ]
