# Generated by Django 4.1.5 on 2023-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20230410_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='categoria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
