# Generated by Django 4.1.5 on 2023-04-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_categoria_in_categoria_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='categoria_in',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='categoria_out',
        ),
    ]
