# Generated by Django 4.1.5 on 2023-01-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='Pessoa Física', max_length=15)),
                ('nome', models.CharField(max_length=50)),
                ('descr', models.CharField(blank=True, max_length=11, null=True)),
                ('valor', models.CharField(blank=True, max_length=20, null=True)),
                ('obs', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_cliente')),
            ],
        ),
    ]
