# Generated by Django 4.1.5 on 2023-01-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='descr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='tipo',
            field=models.CharField(default='Pessoa Física', max_length=20),
        ),
    ]
