# Generated by Django 4.1.5 on 2023-01-14 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=20)),
                ('data_nasc', models.DateField()),
                ('telefone', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=14)),
                ('whatsapp', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=30)),
                ('situacao', models.BooleanField(default=True)),
                ('data_cadastro', models.DateField()),
                ('foto', models.ImageField(upload_to='foto_cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
