# Generated by Django 4.1.5 on 2023-01-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
