# Generated by Django 4.1.5 on 2023-01-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_situacao_client_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ativo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
