# Generated by Django 4.1.5 on 2023-01-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_id_client_cod_cli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_cliente'),
        ),
    ]
