# Generated by Django 4.1.5 on 2023-01-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_bairro_client_cep_client_cidade_client_compl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tipo_end',
            field=models.CharField(default='Residencial', max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='vendedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
