# Generated by Django 4.1.5 on 2023-01-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_client_tipo_end_alter_client_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ativo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
