# Generated by Django 4.1.5 on 2023-01-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_client_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='vendedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
