# Generated by Django 4.1.5 on 2023-03-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=100, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='../media/documents')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='../media/documents')),
                ('data', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
