# Generated by Django 4.1.5 on 2023-03-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='documents',
        ),
    ]
