# Generated by Django 4.1.5 on 2023-04-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_document_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='documento',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='foto',
        ),
    ]
