# Generated by Django 4.1.5 on 2023-04-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0003_rename_documento_documents_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='documents',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
