# Generated by Django 4.1.5 on 2023-03-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='logo1',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='config',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
