# Generated by Django 4.1.5 on 2023-01-18 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_alter_services_descr_alter_services_obs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_remove_employees_id_employees_cod'),
        ('clients', '0016_alter_client_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('produto', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('serie', models.CharField(blank=True, max_length=20, null=True)),
                ('condicao', models.CharField(blank=True, max_length=50, null=True)),
                ('acessorios', models.CharField(blank=True, max_length=50, null=True)),
                ('defeito', models.CharField(blank=True, max_length=50, null=True)),
                ('solucao', models.CharField(blank=True, max_length=50, null=True)),
                ('desconto', models.CharField(blank=True, max_length=50, null=True)),
                ('acressimo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_saída', models.CharField(blank=True, max_length=50, null=True)),
                ('data_alteracao', models.CharField(blank=True, max_length=50, null=True)),
                ('obs', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_cli', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
                ('cod_ser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.services')),
                ('cod_tec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employees')),
                ('cod_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
