# Generated by Django 5.2.1 on 2025-05-21 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('finance', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='work_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('obs_cli', models.CharField(blank=True, max_length=50, null=True)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('produto', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('serie', models.CharField(blank=True, max_length=20, null=True)),
                ('condicao', models.CharField(blank=True, max_length=50, null=True)),
                ('acessorios', models.CharField(blank=True, max_length=50, null=True)),
                ('defeito', models.CharField(blank=True, max_length=50, null=True)),
                ('solucao', models.CharField(blank=True, max_length=50, null=True)),
                ('preco', models.CharField(blank=True, max_length=50, null=True)),
                ('desconto', models.CharField(blank=True, max_length=50, null=True)),
                ('acressimo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_saida', models.CharField(blank=True, max_length=50, null=True)),
                ('data_alteracao', models.CharField(blank=True, max_length=50, null=True)),
                ('obs_ser', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('modo_pgto', models.CharField(blank=True, max_length=50, null=True)),
                ('pgto_adiantado', models.BooleanField()),
                ('os_finalizada', models.BooleanField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.categoria_in')),
                ('cod_cli', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
                ('cod_ser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.services')),
                ('cod_tec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employees')),
                ('cod_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='work_order/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_order.work_order')),
            ],
        ),
    ]
