# Generated by Django 4.1.5 on 2023-01-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='work_order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_order.services')),
            ],
        ),
    ]
