# Generated by Django 4.1.5 on 2023-01-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='modo_pgto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='obs_ser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='os_finalizada',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='pgto_adiantado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='preco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
