# Generated by Django 4.1.5 on 2023-01-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_rename_services_work_order_alter_image_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_order',
            old_name='obs',
            new_name='obs_cli',
        ),
    ]
