# Generated by Django 4.1.5 on 2023-04-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0007_rename_data_saída_work_order_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_order.work_order'),
        ),
    ]
