# Generated by Django 4.1.5 on 2023-04-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0008_alter_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='work_order/'),
        ),
    ]
